spring:
  application:
    name: baribari
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:baribari
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret: test-test-test-test-test-test-test #  openssl rand -base64 32
  access-token-expiry-minutes: 15
  refresh-token-expiry-days: 7
